### PR TITLE
#70 Convert binary MIME types for S3 objects

### LINKED ISSUE #70: Static binary resources on AWS not working properly
When deploying a binary static resource (such as a picture) to AWS, the resource is often not displayed in the browser. The behaviour is not consistent over browsers; sometimes the resource is not shown in Chrome, whereas Safari seems to display correctly. 

Examples:
Deployed with Kotless: https://www.waperon.org
Binary resource: https://www.waperon.org/fjell.jpg
Source-code: https://github.com/pjwalstrom/kotless-test

See also discussion at https://kotlinlang.slack.com/archives/CKS388069/p1603052191057300

Related to https://github.com/JetBrains/kotless/issues/24

### PR DESCRIPTION
**Pull request by mkuzmin**
Fixes #70.

Binary files served from S3 should be converted from base64 to binary format.

### CODE REVIEW

File: engine/src/main/kotlin/io/kotless/gen/factory/route/static/StaticRouteFactory.kt [hunk 1]
```diff
@@ -77,9 +76,10 @@ object StaticRouteFactory : GenerationFactory<Application.ApiGateway.StaticRoute
             status_code = "200"
             responseParameters(mapOf("method.response.header.Content-Type" to "integration.response.header.Content-Type",
                 "method.response.header.Content-Length" to "integration.response.header.Content-Length"))
+            if(context.schema.statics[entity.resource]!!.mime.isBinary)
```
Comment (TanVD) [inline engine/src/main/kotlin/io/kotless/gen/factory/route/static/StaticRouteFactory.kt:79]: A bit of reformatting would be good here :) Should be `if (...)`, use `Reformat file` button :)

**Review by TanVD — APPROVED** [review]
